image: alpine/edge
secrets:
  - ca99d209-296a-41b7-9eda-454250e4b901
environment:
  REPO: ezdl
sources:
  - https://git.sr.ht/~ekoeppen/ezdl
  - https://git.sr.ht/~ekoeppen/build-scripts
tasks:
  - mirror-to-github: ./build-scripts/github-mirror $REPO
