default:
  image: registry.gitlab.com/sbenv/veroxis/images/zig:nightly

stages:
  - build
  - test

build-examples:
  stage: build
  script:
    - apk add git binutils-arm-none-eabi binutils-msp430-elf
    - cd ${CI_PROJECT_DIR}/examples/empty
    - zig build -Drelease-small -Dboard=ezdl/src/stm32/boards/nucleo_f072rb
    - zig build -Drelease-small -Dboard=ezdl/src/msp430/boards/exp_msp430g2
