default:
  image: registry.gitlab.com/sbenv/veroxis/images/zig:nightly

stages:
  - build
  - test

build-examples:
  stage: build
  script:
    - zig run src/testing/examples.zig -- src/testing/examples.json > examples.xml
  artifacts:
    when: always
    paths:
      - examples.xml
      - "examples/stm32/*/zig-out/bin/*.elf"
      - "examples/generic/*/zig-out/bin/*.elf"
    reports:
      junit: examples.xml
